/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext;

import oliv.form.xtext.dsl.*;
import oliv.form.xtext.dsl.impl.DslFactoryImpl;
import oliv.form.xtext.dsl.impl.VariableCalculeImpl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class DslFactoryImplOliv extends DslFactoryImpl 
{
  

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableCalcule createVariableCalcule()
  {
    VariableCalculeImpl variableCalcule = new VariableCalculeOliv();
    return variableCalcule;
  }

} //DslFactoryImpl
