/*
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.serializer;

import com.google.inject.Inject;
import java.util.Set;
import oliv.form.xtext.fix.fix.FixPackage;
import oliv.form.xtext.fix.fix.Greeting;
import oliv.form.xtext.fix.fix.Model;
import oliv.form.xtext.fix.services.FixGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class FixSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private FixGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == FixPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case FixPackage.GREETING:
				sequence_Greeting(context, (Greeting) semanticObject); 
				return; 
			case FixPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Greeting returns Greeting
	 *
	 * Constraint:
	 *     (name=ID points+=Point)
	 */
	protected void sequence_Greeting(ISerializationContext context, Greeting semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     greetings+=Greeting+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
