/**
	 * generated by Xtext 2.21.0
*/
package oliv.form.xtext.dsl.impl;

import oliv.form.xtext.dsl.Import;

// This class overrides the generated class and will be instantiated by factory
public class ImportImpl extends MImportImpl implements Import
{

}
