/**
	 * generated by Xtext 2.21.0
*/
package oliv.form.xtext.dsl.impl;

import oliv.form.xtext.dsl.VariableCalcule;

// This class overrides the generated class and will be instantiated by factory
public class VariableCalculeImpl extends MVariableCalculeImpl implements VariableCalcule
{

}
