/**
	 * generated by Xtext 2.21.0
*/
package oliv.form.xtext.dsl.impl;

import oliv.form.xtext.dsl.VariableCalcule;

// This class overrides the generated class and will be instantiated by factory
public class VariableCalculeImpl extends MVariableCalculeImpl implements VariableCalcule
{
	@Override
	public String getNom() {
		return super.getName();
	}
	@Override
	public double getValeurs() {
		double valeur;
		try{
			 valeur =calculator.evaluate(((VariableCalcule)v).getExpression());
		}
		catch (IllegalArgumentException e) {
			 valeur =0.0;
		}
		return valeur;
	}
}
