/**
	 * generated by Xtext 2.21.0
*/
package oliv.form.xtext.dsl.impl;

import oliv.form.xtext.dsl.VariableDev;

// This class overrides the generated class and will be instantiated by factory
public class VariableDevImpl extends VariableImpl implements VariableDev
{
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return super.toString()+"Salut";
	}
}
