/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see oliv.form.xtext.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.form.oliv/xtext/Dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DslPackage eINSTANCE = oliv.form.xtext.dsl.impl.DslPackageImpl.init();

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.ModelImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__VARIABLES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.TrucImpl <em>Truc</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.TrucImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getTruc()
   * @generated
   */
  int TRUC = 1;

  /**
   * The number of structural features of the '<em>Truc</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRUC_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.AutreImpl <em>Autre</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.AutreImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getAutre()
   * @generated
   */
  int AUTRE = 2;

  /**
   * The feature id for the '<em><b>Bob</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTRE__BOB = TRUC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Autre</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTRE_FEATURE_COUNT = TRUC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.VariableImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 3;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.VariableDirectImpl <em>Variable Direct</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.VariableDirectImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariableDirect()
   * @generated
   */
  int VARIABLE_DIRECT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DIRECT__NAME = TRUC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Alpha</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DIRECT__ALPHA = TRUC_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Beta</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DIRECT__BETA = TRUC_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Variable Direct</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DIRECT_FEATURE_COUNT = TRUC_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.VariableCalculeImpl <em>Variable Calcule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.VariableCalculeImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariableCalcule()
   * @generated
   */
  int VARIABLE_CALCULE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_CALCULE__NAME = TRUC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_CALCULE__EXPRESSION = TRUC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Calcule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_CALCULE_FEATURE_COUNT = TRUC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.ExpressionImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 6;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.PlusImpl <em>Plus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.PlusImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getPlus()
   * @generated
   */
  int PLUS = 7;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Plus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.MinusImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getMinus()
   * @generated
   */
  int MINUS = 8;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MultiImpl <em>Multi</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.MultiImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getMulti()
   * @generated
   */
  int MULTI = 9;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multi</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTI_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.DivImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getDiv()
   * @generated
   */
  int DIV = 10;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.NumberLiteralImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link oliv.form.xtext.dsl.impl.VariableExpressionImpl <em>Variable Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.dsl.impl.VariableExpressionImpl
   * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariableExpression()
   * @generated
   */
  int VARIABLE_EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_EXPRESSION__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see oliv.form.xtext.dsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link oliv.form.xtext.dsl.Model#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see oliv.form.xtext.dsl.Model#getVariables()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Variables();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Truc <em>Truc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Truc</em>'.
   * @see oliv.form.xtext.dsl.Truc
   * @generated
   */
  EClass getTruc();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Autre <em>Autre</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Autre</em>'.
   * @see oliv.form.xtext.dsl.Autre
   * @generated
   */
  EClass getAutre();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.Autre#getBob <em>Bob</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bob</em>'.
   * @see oliv.form.xtext.dsl.Autre#getBob()
   * @see #getAutre()
   * @generated
   */
  EAttribute getAutre_Bob();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see oliv.form.xtext.dsl.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.VariableDirect <em>Variable Direct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Direct</em>'.
   * @see oliv.form.xtext.dsl.VariableDirect
   * @generated
   */
  EClass getVariableDirect();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.VariableDirect#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oliv.form.xtext.dsl.VariableDirect#getName()
   * @see #getVariableDirect()
   * @generated
   */
  EAttribute getVariableDirect_Name();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.VariableDirect#getAlpha <em>Alpha</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Alpha</em>'.
   * @see oliv.form.xtext.dsl.VariableDirect#getAlpha()
   * @see #getVariableDirect()
   * @generated
   */
  EAttribute getVariableDirect_Alpha();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.VariableDirect#getBeta <em>Beta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Beta</em>'.
   * @see oliv.form.xtext.dsl.VariableDirect#getBeta()
   * @see #getVariableDirect()
   * @generated
   */
  EAttribute getVariableDirect_Beta();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.VariableCalcule <em>Variable Calcule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Calcule</em>'.
   * @see oliv.form.xtext.dsl.VariableCalcule
   * @generated
   */
  EClass getVariableCalcule();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.VariableCalcule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oliv.form.xtext.dsl.VariableCalcule#getName()
   * @see #getVariableCalcule()
   * @generated
   */
  EAttribute getVariableCalcule_Name();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.VariableCalcule#getExpression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expression</em>'.
   * @see oliv.form.xtext.dsl.VariableCalcule#getExpression()
   * @see #getVariableCalcule()
   * @generated
   */
  EReference getVariableCalcule_Expression();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see oliv.form.xtext.dsl.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Plus <em>Plus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Plus</em>'.
   * @see oliv.form.xtext.dsl.Plus
   * @generated
   */
  EClass getPlus();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Plus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see oliv.form.xtext.dsl.Plus#getLeft()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Left();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Plus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see oliv.form.xtext.dsl.Plus#getRight()
   * @see #getPlus()
   * @generated
   */
  EReference getPlus_Right();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see oliv.form.xtext.dsl.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see oliv.form.xtext.dsl.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see oliv.form.xtext.dsl.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Multi <em>Multi</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multi</em>'.
   * @see oliv.form.xtext.dsl.Multi
   * @generated
   */
  EClass getMulti();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Multi#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see oliv.form.xtext.dsl.Multi#getLeft()
   * @see #getMulti()
   * @generated
   */
  EReference getMulti_Left();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Multi#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see oliv.form.xtext.dsl.Multi#getRight()
   * @see #getMulti()
   * @generated
   */
  EReference getMulti_Right();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see oliv.form.xtext.dsl.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Div#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see oliv.form.xtext.dsl.Div#getLeft()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Left();

  /**
   * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.Div#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see oliv.form.xtext.dsl.Div#getRight()
   * @see #getDiv()
   * @generated
   */
  EReference getDiv_Right();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see oliv.form.xtext.dsl.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see oliv.form.xtext.dsl.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.dsl.VariableExpression <em>Variable Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Expression</em>'.
   * @see oliv.form.xtext.dsl.VariableExpression
   * @generated
   */
  EClass getVariableExpression();

  /**
   * Returns the meta object for the reference '{@link oliv.form.xtext.dsl.VariableExpression#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Value</em>'.
   * @see oliv.form.xtext.dsl.VariableExpression#getValue()
   * @see #getVariableExpression()
   * @generated
   */
  EReference getVariableExpression_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DslFactory getDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.ModelImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__VARIABLES = eINSTANCE.getModel_Variables();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.TrucImpl <em>Truc</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.TrucImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getTruc()
     * @generated
     */
    EClass TRUC = eINSTANCE.getTruc();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.AutreImpl <em>Autre</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.AutreImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getAutre()
     * @generated
     */
    EClass AUTRE = eINSTANCE.getAutre();

    /**
     * The meta object literal for the '<em><b>Bob</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AUTRE__BOB = eINSTANCE.getAutre_Bob();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.VariableImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.VariableDirectImpl <em>Variable Direct</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.VariableDirectImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariableDirect()
     * @generated
     */
    EClass VARIABLE_DIRECT = eINSTANCE.getVariableDirect();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DIRECT__NAME = eINSTANCE.getVariableDirect_Name();

    /**
     * The meta object literal for the '<em><b>Alpha</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DIRECT__ALPHA = eINSTANCE.getVariableDirect_Alpha();

    /**
     * The meta object literal for the '<em><b>Beta</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DIRECT__BETA = eINSTANCE.getVariableDirect_Beta();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.VariableCalculeImpl <em>Variable Calcule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.VariableCalculeImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariableCalcule()
     * @generated
     */
    EClass VARIABLE_CALCULE = eINSTANCE.getVariableCalcule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_CALCULE__NAME = eINSTANCE.getVariableCalcule_Name();

    /**
     * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_CALCULE__EXPRESSION = eINSTANCE.getVariableCalcule_Expression();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.ExpressionImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.PlusImpl <em>Plus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.PlusImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getPlus()
     * @generated
     */
    EClass PLUS = eINSTANCE.getPlus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.MinusImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MultiImpl <em>Multi</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.MultiImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getMulti()
     * @generated
     */
    EClass MULTI = eINSTANCE.getMulti();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTI__LEFT = eINSTANCE.getMulti_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTI__RIGHT = eINSTANCE.getMulti_Right();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.DivImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__LEFT = eINSTANCE.getDiv_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV__RIGHT = eINSTANCE.getDiv_Right();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.NumberLiteralImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.VariableExpressionImpl <em>Variable Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.dsl.impl.VariableExpressionImpl
     * @see oliv.form.xtext.dsl.impl.DslPackageImpl#getVariableExpression()
     * @generated
     */
    EClass VARIABLE_EXPRESSION = eINSTANCE.getVariableExpression();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIABLE_EXPRESSION__VALUE = eINSTANCE.getVariableExpression_Value();

  }

} //DslPackage
