/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see oliv.form.xtext.dsl.MDslFactory
 * @model kind="package"
 * @generated
 */
public interface MDslPackage extends EPackage {
	/**
	 * The package name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNAME = "dsl";

	/**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_URI = "http://www.form.oliv/xtext/Dsl";

	/**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	String eNS_PREFIX = "dsl";

	/**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	MDslPackage eINSTANCE = oliv.form.xtext.dsl.impl.MDslPackageImpl.init();

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MModelImpl <em>Model</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MModelImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getModel()
	 * @generated
	 */
	int MODEL = 0;

	/**
	 * The feature id for the '<em><b>Variables</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MODEL__VARIABLES = 0;

	/**
	 * The number of structural features of the '<em>Model</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MODEL_FEATURE_COUNT = 1;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MTrucImpl <em>Truc</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MTrucImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getTruc()
	 * @generated
	 */
	int TRUC = 1;

	/**
	 * The number of structural features of the '<em>Truc</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int TRUC_FEATURE_COUNT = 0;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MAutreImpl <em>Autre</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MAutreImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getAutre()
	 * @generated
	 */
	int AUTRE = 2;

	/**
	 * The feature id for the '<em><b>Bob</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int AUTRE__BOB = TRUC_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Autre</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int AUTRE_FEATURE_COUNT = TRUC_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MVariableImpl <em>Variable</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MVariableImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariable()
	 * @generated
	 */
	int VARIABLE = 3;

	/**
	 * The number of structural features of the '<em>Variable</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_FEATURE_COUNT = 0;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MVariableDirectImpl <em>Variable Direct</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MVariableDirectImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariableDirect()
	 * @generated
	 */
	int VARIABLE_DIRECT = 4;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_DIRECT__NAME = TRUC_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Alpha</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_DIRECT__ALPHA = TRUC_FEATURE_COUNT + 1;

	/**
	 * The feature id for the '<em><b>Beta</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_DIRECT__BETA = TRUC_FEATURE_COUNT + 2;

	/**
	 * The number of structural features of the '<em>Variable Direct</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_DIRECT_FEATURE_COUNT = TRUC_FEATURE_COUNT + 3;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MVariableCalculeImpl <em>Variable Calcule</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MVariableCalculeImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariableCalcule()
	 * @generated
	 */
	int VARIABLE_CALCULE = 5;

	/**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_CALCULE__NAME = TRUC_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Expression</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_CALCULE__EXPRESSION = TRUC_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Variable Calcule</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_CALCULE_FEATURE_COUNT = TRUC_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MExpressionImpl <em>Expression</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MExpressionImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getExpression()
	 * @generated
	 */
	int EXPRESSION = 6;

	/**
	 * The number of structural features of the '<em>Expression</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int EXPRESSION_FEATURE_COUNT = 0;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MPlusImpl <em>Plus</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MPlusImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getPlus()
	 * @generated
	 */
	int PLUS = 7;

	/**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PLUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PLUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Plus</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int PLUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MMinusImpl <em>Minus</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MMinusImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getMinus()
	 * @generated
	 */
	int MINUS = 8;

	/**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Minus</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MMultiImpl <em>Multi</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MMultiImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getMulti()
	 * @generated
	 */
	int MULTI = 9;

	/**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MULTI__LEFT = EXPRESSION_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MULTI__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Multi</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int MULTI_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MDivImpl <em>Div</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MDivImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getDiv()
	 * @generated
	 */
	int DIV = 10;

	/**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DIV__LEFT = EXPRESSION_FEATURE_COUNT + 0;

	/**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DIV__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

	/**
	 * The number of structural features of the '<em>Div</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int DIV_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MNumberLiteralImpl <em>Number Literal</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MNumberLiteralImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getNumberLiteral()
	 * @generated
	 */
	int NUMBER_LITERAL = 11;

	/**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int NUMBER_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Number Literal</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int NUMBER_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

	/**
	 * The meta object id for the '{@link oliv.form.xtext.dsl.impl.MVariableExpressionImpl <em>Variable Expression</em>}' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see oliv.form.xtext.dsl.impl.MVariableExpressionImpl
	 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariableExpression()
	 * @generated
	 */
	int VARIABLE_EXPRESSION = 12;

	/**
	 * The feature id for the '<em><b>Value</b></em>' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_EXPRESSION__VALUE = EXPRESSION_FEATURE_COUNT + 0;

	/**
	 * The number of structural features of the '<em>Variable Expression</em>' class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
	int VARIABLE_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MModel <em>Model</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Model</em>'.
	 * @see oliv.form.xtext.dsl.MModel
	 * @generated
	 */
	EClass getModel();

	/**
	 * Returns the meta object for the containment reference list '{@link oliv.form.xtext.dsl.MModel#getVariables <em>Variables</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Variables</em>'.
	 * @see oliv.form.xtext.dsl.MModel#getVariables()
	 * @see #getModel()
	 * @generated
	 */
	EReference getModel_Variables();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MTruc <em>Truc</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Truc</em>'.
	 * @see oliv.form.xtext.dsl.MTruc
	 * @generated
	 */
	EClass getTruc();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MAutre <em>Autre</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Autre</em>'.
	 * @see oliv.form.xtext.dsl.MAutre
	 * @generated
	 */
	EClass getAutre();

	/**
	 * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.MAutre#getBob <em>Bob</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Bob</em>'.
	 * @see oliv.form.xtext.dsl.MAutre#getBob()
	 * @see #getAutre()
	 * @generated
	 */
	EAttribute getAutre_Bob();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MVariable <em>Variable</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Variable</em>'.
	 * @see oliv.form.xtext.dsl.MVariable
	 * @generated
	 */
	EClass getVariable();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MVariableDirect <em>Variable Direct</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Variable Direct</em>'.
	 * @see oliv.form.xtext.dsl.MVariableDirect
	 * @generated
	 */
	EClass getVariableDirect();

	/**
	 * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.MVariableDirect#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see oliv.form.xtext.dsl.MVariableDirect#getName()
	 * @see #getVariableDirect()
	 * @generated
	 */
	EAttribute getVariableDirect_Name();

	/**
	 * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.MVariableDirect#getAlpha <em>Alpha</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Alpha</em>'.
	 * @see oliv.form.xtext.dsl.MVariableDirect#getAlpha()
	 * @see #getVariableDirect()
	 * @generated
	 */
	EAttribute getVariableDirect_Alpha();

	/**
	 * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.MVariableDirect#getBeta <em>Beta</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Beta</em>'.
	 * @see oliv.form.xtext.dsl.MVariableDirect#getBeta()
	 * @see #getVariableDirect()
	 * @generated
	 */
	EAttribute getVariableDirect_Beta();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MVariableCalcule <em>Variable Calcule</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Variable Calcule</em>'.
	 * @see oliv.form.xtext.dsl.MVariableCalcule
	 * @generated
	 */
	EClass getVariableCalcule();

	/**
	 * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.MVariableCalcule#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see oliv.form.xtext.dsl.MVariableCalcule#getName()
	 * @see #getVariableCalcule()
	 * @generated
	 */
	EAttribute getVariableCalcule_Name();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MVariableCalcule#getExpression <em>Expression</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Expression</em>'.
	 * @see oliv.form.xtext.dsl.MVariableCalcule#getExpression()
	 * @see #getVariableCalcule()
	 * @generated
	 */
	EReference getVariableCalcule_Expression();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MExpression <em>Expression</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Expression</em>'.
	 * @see oliv.form.xtext.dsl.MExpression
	 * @generated
	 */
	EClass getExpression();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MPlus <em>Plus</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Plus</em>'.
	 * @see oliv.form.xtext.dsl.MPlus
	 * @generated
	 */
	EClass getPlus();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MPlus#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see oliv.form.xtext.dsl.MPlus#getLeft()
	 * @see #getPlus()
	 * @generated
	 */
	EReference getPlus_Left();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MPlus#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see oliv.form.xtext.dsl.MPlus#getRight()
	 * @see #getPlus()
	 * @generated
	 */
	EReference getPlus_Right();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MMinus <em>Minus</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Minus</em>'.
	 * @see oliv.form.xtext.dsl.MMinus
	 * @generated
	 */
	EClass getMinus();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MMinus#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see oliv.form.xtext.dsl.MMinus#getLeft()
	 * @see #getMinus()
	 * @generated
	 */
	EReference getMinus_Left();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MMinus#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see oliv.form.xtext.dsl.MMinus#getRight()
	 * @see #getMinus()
	 * @generated
	 */
	EReference getMinus_Right();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MMulti <em>Multi</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Multi</em>'.
	 * @see oliv.form.xtext.dsl.MMulti
	 * @generated
	 */
	EClass getMulti();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MMulti#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see oliv.form.xtext.dsl.MMulti#getLeft()
	 * @see #getMulti()
	 * @generated
	 */
	EReference getMulti_Left();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MMulti#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see oliv.form.xtext.dsl.MMulti#getRight()
	 * @see #getMulti()
	 * @generated
	 */
	EReference getMulti_Right();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MDiv <em>Div</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Div</em>'.
	 * @see oliv.form.xtext.dsl.MDiv
	 * @generated
	 */
	EClass getDiv();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MDiv#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see oliv.form.xtext.dsl.MDiv#getLeft()
	 * @see #getDiv()
	 * @generated
	 */
	EReference getDiv_Left();

	/**
	 * Returns the meta object for the containment reference '{@link oliv.form.xtext.dsl.MDiv#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see oliv.form.xtext.dsl.MDiv#getRight()
	 * @see #getDiv()
	 * @generated
	 */
	EReference getDiv_Right();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MNumberLiteral <em>Number Literal</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Number Literal</em>'.
	 * @see oliv.form.xtext.dsl.MNumberLiteral
	 * @generated
	 */
	EClass getNumberLiteral();

	/**
	 * Returns the meta object for the attribute '{@link oliv.form.xtext.dsl.MNumberLiteral#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see oliv.form.xtext.dsl.MNumberLiteral#getValue()
	 * @see #getNumberLiteral()
	 * @generated
	 */
	EAttribute getNumberLiteral_Value();

	/**
	 * Returns the meta object for class '{@link oliv.form.xtext.dsl.MVariableExpression <em>Variable Expression</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Variable Expression</em>'.
	 * @see oliv.form.xtext.dsl.MVariableExpression
	 * @generated
	 */
	EClass getVariableExpression();

	/**
	 * Returns the meta object for the reference '{@link oliv.form.xtext.dsl.MVariableExpression#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Value</em>'.
	 * @see oliv.form.xtext.dsl.MVariableExpression#getValue()
	 * @see #getVariableExpression()
	 * @generated
	 */
	EReference getVariableExpression_Value();

	/**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
	MDslFactory getDslFactory();

	/**
	 * <!-- begin-user-doc -->
	 * Defines literals for the meta objects that represent
	 * <ul>
	 *   <li>each class,</li>
	 *   <li>each feature of each class,</li>
	 *   <li>each enum,</li>
	 *   <li>and each data type</li>
	 * </ul>
	 * <!-- end-user-doc -->
	 * @generated
	 */
	interface Literals {
		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MModelImpl <em>Model</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MModelImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getModel()
		 * @generated
		 */
		EClass MODEL = eINSTANCE.getModel();

		/**
		 * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference MODEL__VARIABLES = eINSTANCE.getModel_Variables();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MTrucImpl <em>Truc</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MTrucImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getTruc()
		 * @generated
		 */
		EClass TRUC = eINSTANCE.getTruc();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MAutreImpl <em>Autre</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MAutreImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getAutre()
		 * @generated
		 */
		EClass AUTRE = eINSTANCE.getAutre();

		/**
		 * The meta object literal for the '<em><b>Bob</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute AUTRE__BOB = eINSTANCE.getAutre_Bob();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MVariableImpl <em>Variable</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MVariableImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariable()
		 * @generated
		 */
		EClass VARIABLE = eINSTANCE.getVariable();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MVariableDirectImpl <em>Variable Direct</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MVariableDirectImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariableDirect()
		 * @generated
		 */
		EClass VARIABLE_DIRECT = eINSTANCE.getVariableDirect();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute VARIABLE_DIRECT__NAME = eINSTANCE.getVariableDirect_Name();

		/**
		 * The meta object literal for the '<em><b>Alpha</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute VARIABLE_DIRECT__ALPHA = eINSTANCE.getVariableDirect_Alpha();

		/**
		 * The meta object literal for the '<em><b>Beta</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute VARIABLE_DIRECT__BETA = eINSTANCE.getVariableDirect_Beta();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MVariableCalculeImpl <em>Variable Calcule</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MVariableCalculeImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariableCalcule()
		 * @generated
		 */
		EClass VARIABLE_CALCULE = eINSTANCE.getVariableCalcule();

		/**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute VARIABLE_CALCULE__NAME = eINSTANCE.getVariableCalcule_Name();

		/**
		 * The meta object literal for the '<em><b>Expression</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference VARIABLE_CALCULE__EXPRESSION = eINSTANCE.getVariableCalcule_Expression();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MExpressionImpl <em>Expression</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MExpressionImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getExpression()
		 * @generated
		 */
		EClass EXPRESSION = eINSTANCE.getExpression();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MPlusImpl <em>Plus</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MPlusImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getPlus()
		 * @generated
		 */
		EClass PLUS = eINSTANCE.getPlus();

		/**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference PLUS__LEFT = eINSTANCE.getPlus_Left();

		/**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference PLUS__RIGHT = eINSTANCE.getPlus_Right();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MMinusImpl <em>Minus</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MMinusImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getMinus()
		 * @generated
		 */
		EClass MINUS = eINSTANCE.getMinus();

		/**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

		/**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MMultiImpl <em>Multi</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MMultiImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getMulti()
		 * @generated
		 */
		EClass MULTI = eINSTANCE.getMulti();

		/**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference MULTI__LEFT = eINSTANCE.getMulti_Left();

		/**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference MULTI__RIGHT = eINSTANCE.getMulti_Right();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MDivImpl <em>Div</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MDivImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getDiv()
		 * @generated
		 */
		EClass DIV = eINSTANCE.getDiv();

		/**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DIV__LEFT = eINSTANCE.getDiv_Left();

		/**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference DIV__RIGHT = eINSTANCE.getDiv_Right();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MNumberLiteralImpl <em>Number Literal</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MNumberLiteralImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getNumberLiteral()
		 * @generated
		 */
		EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

		/**
		 * The meta object literal for the '{@link oliv.form.xtext.dsl.impl.MVariableExpressionImpl <em>Variable Expression</em>}' class.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @see oliv.form.xtext.dsl.impl.MVariableExpressionImpl
		 * @see oliv.form.xtext.dsl.impl.MDslPackageImpl#getVariableExpression()
		 * @generated
		 */
		EClass VARIABLE_EXPRESSION = eINSTANCE.getVariableExpression();

		/**
		 * The meta object literal for the '<em><b>Value</b></em>' reference feature.
		 * <!-- begin-user-doc -->
		 * <!-- end-user-doc -->
		 * @generated
		 */
		EReference VARIABLE_EXPRESSION__VALUE = eINSTANCE.getVariableExpression_Value();

	}

} //MDslPackage
