/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see oliv.form.xtext.dsl.MDslPackage#getVariable()
 * @model
 * @generated
 */
public interface MVariable extends EObject {
} // MVariable
