/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Calcule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oliv.form.xtext.dsl.MVariableCalcule#getName <em>Name</em>}</li>
 *   <li>{@link oliv.form.xtext.dsl.MVariableCalcule#getExpression <em>Expression</em>}</li>
 *   <li>{@link oliv.form.xtext.dsl.MVariableCalcule#getExpression2 <em>Expression2</em>}</li>
 * </ul>
 *
 * @see oliv.form.xtext.dsl.MDslPackage#getVariableCalcule()
 * @model
 * @generated
 */
public interface MVariableCalcule extends Truc, Variable {
	/**
	 * Returns the value of the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Name</em>' attribute.
	 * @see #setName(String)
	 * @see oliv.form.xtext.dsl.MDslPackage#getVariableCalcule_Name()
	 * @model
	 * @generated
	 */
	String getName();

	/**
	 * Sets the value of the '{@link oliv.form.xtext.dsl.MVariableCalcule#getName <em>Name</em>}' attribute.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Name</em>' attribute.
	 * @see #getName()
	 * @generated
	 */
	void setName(String value);

	/**
	 * Returns the value of the '<em><b>Expression</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Expression</em>' containment reference.
	 * @see #setExpression(Expression)
	 * @see oliv.form.xtext.dsl.MDslPackage#getVariableCalcule_Expression()
	 * @model containment="true"
	 * @generated
	 */
	Expression getExpression();

	/**
	 * Sets the value of the '{@link oliv.form.xtext.dsl.MVariableCalcule#getExpression <em>Expression</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Expression</em>' containment reference.
	 * @see #getExpression()
	 * @generated
	 */
	void setExpression(Expression value);

	/**
	 * Returns the value of the '<em><b>Expression2</b></em>' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @return the value of the '<em>Expression2</em>' containment reference.
	 * @see #setExpression2(Expression)
	 * @see oliv.form.xtext.dsl.MDslPackage#getVariableCalcule_Expression2()
	 * @model containment="true"
	 * @generated
	 */
	Expression getExpression2();

	/**
	 * Sets the value of the '{@link oliv.form.xtext.dsl.MVariableCalcule#getExpression2 <em>Expression2</em>}' containment reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Expression2</em>' containment reference.
	 * @see #getExpression2()
	 * @generated
	 */
	void setExpression2(Expression value);

} // MVariableCalcule
