/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Truc</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see oliv.form.xtext.dsl.DslPackage#getTruc()
 * @model
 * @generated
 */
public interface Truc extends EObject
{
} // Truc
