/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oliv.form.xtext.dsl.VariableExpression#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see oliv.form.xtext.dsl.DslPackage#getVariableExpression()
 * @model
 * @generated
 */
public interface VariableExpression extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(Variable)
   * @see oliv.form.xtext.dsl.DslPackage#getVariableExpression_Value()
   * @model
   * @generated
   */
  Variable getValue();

  /**
   * Sets the value of the '{@link oliv.form.xtext.dsl.VariableExpression#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Variable value);

} // VariableExpression
