/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.fix;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Courbe</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oliv.form.xtext.fix.fix.Courbe#getName <em>Name</em>}</li>
 *   <li>{@link oliv.form.xtext.fix.fix.Courbe#getLignes <em>Lignes</em>}</li>
 * </ul>
 *
 * @see oliv.form.xtext.fix.fix.FixPackage#getCourbe()
 * @model
 * @generated
 */
public interface Courbe extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see oliv.form.xtext.fix.fix.FixPackage#getCourbe_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link oliv.form.xtext.fix.fix.Courbe#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Lignes</b></em>' containment reference list.
   * The list contents are of type {@link oliv.form.xtext.fix.fix.Ligne}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lignes</em>' containment reference list.
   * @see oliv.form.xtext.fix.fix.FixPackage#getCourbe_Lignes()
   * @model containment="true"
   * @generated
   */
  EList<Ligne> getLignes();

} // Courbe
