/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.fix;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see oliv.form.xtext.fix.fix.FixFactory
 * @model kind="package"
 * @generated
 */
public interface FixPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "fix";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.form.oliv/xtext/fix/Fix";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "fix";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FixPackage eINSTANCE = oliv.form.xtext.fix.fix.impl.FixPackageImpl.init();

  /**
   * The meta object id for the '{@link oliv.form.xtext.fix.fix.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.fix.fix.impl.ModelImpl
   * @see oliv.form.xtext.fix.fix.impl.FixPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Courbes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COURBES = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link oliv.form.xtext.fix.fix.impl.CourbeImpl <em>Courbe</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.fix.fix.impl.CourbeImpl
   * @see oliv.form.xtext.fix.fix.impl.FixPackageImpl#getCourbe()
   * @generated
   */
  int COURBE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURBE__NAME = 0;

  /**
   * The feature id for the '<em><b>Lignes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURBE__LIGNES = 1;

  /**
   * The number of structural features of the '<em>Courbe</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COURBE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link oliv.form.xtext.fix.fix.impl.LigneImpl <em>Ligne</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see oliv.form.xtext.fix.fix.impl.LigneImpl
   * @see oliv.form.xtext.fix.fix.impl.FixPackageImpl#getLigne()
   * @generated
   */
  int LIGNE = 2;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE__Y = 1;

  /**
   * The number of structural features of the '<em>Ligne</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LIGNE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link oliv.form.xtext.fix.fix.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see oliv.form.xtext.fix.fix.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link oliv.form.xtext.fix.fix.Model#getCourbes <em>Courbes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Courbes</em>'.
   * @see oliv.form.xtext.fix.fix.Model#getCourbes()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Courbes();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.fix.fix.Courbe <em>Courbe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Courbe</em>'.
   * @see oliv.form.xtext.fix.fix.Courbe
   * @generated
   */
  EClass getCourbe();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.fix.fix.Courbe#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see oliv.form.xtext.fix.fix.Courbe#getName()
   * @see #getCourbe()
   * @generated
   */
  EAttribute getCourbe_Name();

  /**
   * Returns the meta object for the containment reference list '{@link oliv.form.xtext.fix.fix.Courbe#getLignes <em>Lignes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Lignes</em>'.
   * @see oliv.form.xtext.fix.fix.Courbe#getLignes()
   * @see #getCourbe()
   * @generated
   */
  EReference getCourbe_Lignes();

  /**
   * Returns the meta object for class '{@link oliv.form.xtext.fix.fix.Ligne <em>Ligne</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ligne</em>'.
   * @see oliv.form.xtext.fix.fix.Ligne
   * @generated
   */
  EClass getLigne();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.fix.fix.Ligne#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see oliv.form.xtext.fix.fix.Ligne#getX()
   * @see #getLigne()
   * @generated
   */
  EAttribute getLigne_X();

  /**
   * Returns the meta object for the attribute '{@link oliv.form.xtext.fix.fix.Ligne#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see oliv.form.xtext.fix.fix.Ligne#getY()
   * @see #getLigne()
   * @generated
   */
  EAttribute getLigne_Y();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FixFactory getFixFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link oliv.form.xtext.fix.fix.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.fix.fix.impl.ModelImpl
     * @see oliv.form.xtext.fix.fix.impl.FixPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Courbes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COURBES = eINSTANCE.getModel_Courbes();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.fix.fix.impl.CourbeImpl <em>Courbe</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.fix.fix.impl.CourbeImpl
     * @see oliv.form.xtext.fix.fix.impl.FixPackageImpl#getCourbe()
     * @generated
     */
    EClass COURBE = eINSTANCE.getCourbe();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COURBE__NAME = eINSTANCE.getCourbe_Name();

    /**
     * The meta object literal for the '<em><b>Lignes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COURBE__LIGNES = eINSTANCE.getCourbe_Lignes();

    /**
     * The meta object literal for the '{@link oliv.form.xtext.fix.fix.impl.LigneImpl <em>Ligne</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see oliv.form.xtext.fix.fix.impl.LigneImpl
     * @see oliv.form.xtext.fix.fix.impl.FixPackageImpl#getLigne()
     * @generated
     */
    EClass LIGNE = eINSTANCE.getLigne();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGNE__X = eINSTANCE.getLigne_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LIGNE__Y = eINSTANCE.getLigne_Y();

  }

} //FixPackage
