/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.fix;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greeting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oliv.form.xtext.fix.fix.Greeting#getName <em>Name</em>}</li>
 *   <li>{@link oliv.form.xtext.fix.fix.Greeting#getPoints <em>Points</em>}</li>
 * </ul>
 *
 * @see oliv.form.xtext.fix.fix.FixPackage#getGreeting()
 * @model
 * @generated
 */
public interface Greeting extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see oliv.form.xtext.fix.fix.FixPackage#getGreeting_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link oliv.form.xtext.fix.fix.Greeting#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Points</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' attribute list.
   * @see oliv.form.xtext.fix.fix.FixPackage#getGreeting_Points()
   * @model unique="false"
   * @generated
   */
  EList<String> getPoints();

} // Greeting
