/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.fix;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link oliv.form.xtext.fix.fix.Model#getCourbes <em>Courbes</em>}</li>
 * </ul>
 *
 * @see oliv.form.xtext.fix.fix.FixPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Courbes</b></em>' containment reference list.
   * The list contents are of type {@link oliv.form.xtext.fix.fix.Courbe}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Courbes</em>' containment reference list.
   * @see oliv.form.xtext.fix.fix.FixPackage#getModel_Courbes()
   * @model containment="true"
   * @generated
   */
  EList<Courbe> getCourbes();

} // Model
