/*
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.ui.tests;

import com.google.inject.Injector;
import oliv.form.xtext.fix.ui.internal.FixActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class FixUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FixActivator.getInstance().getInjector("oliv.form.xtext.fix.Fix");
	}

}
