/*
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FixUiModule extends AbstractFixUiModule {

	public FixUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
