/*
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFixScopeProvider extends DelegatingScopeProvider {
}
