/*
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class FixProposalProvider extends AbstractFixProposalProvider {
}
