/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl.impl;

import oliv.form.xtext.dsl.MDslPackage;
import oliv.form.xtext.dsl.Truc;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Truc</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MTrucImpl extends MinimalEObjectImpl.Container implements Truc {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MTrucImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MDslPackage.Literals.TRUC;
	}

} //MTrucImpl
