/**
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.dsl.impl;

import oliv.form.xtext.dsl.MDslPackage;
import oliv.form.xtext.dsl.Variable;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MVariableImpl extends MinimalEObjectImpl.Container implements Variable {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MVariableImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return MDslPackage.Literals.VARIABLE;
	}

} //MVariableImpl
