/**
	 * generated by Xtext 2.21.0
*/
package oliv.form.xtext.dsl;

import oliv.form.xtext.dsl.impl.DslFactoryImpl;

/** This factory  overrides the generated factory and returns the new generated interfaces */
public interface DslFactory extends MDslFactory 
{
	
	/** Specialize the eINSTANCE initialization with the new interface type 
	  * (overridden in the override_factory extension)
	*/
	DslFactory eINSTANCE = DslFactoryImpl.init();
				
}
