/**
	 * generated by Xtext 2.21.0
*/
package oliv.form.xtext.dsl;
		
/** This package interface extends  the generated package interface 
    It is necessary because its name is used in the EMF generated code) 
*/
public interface DslPackage extends MDslPackage 
{
	interface Literals extends MDslPackage.Literals{};
	
	
}
