/**
	 * generated by Xtext 2.21.0
*/
package oliv.form.xtext.dsl;

// This interface overrides the generated interface and will be returned by factory
public interface Variable extends MVariable
{
	// You can write additional methods using an empty default java 8 notation 
	// because the generated implemented class extends this interface and is not abstract
	//
	// For instance : 
	// default public void addSomething(Something foo) {} ;
	default String  getNom() {
		return "Salut";
	}
}
