/*
 * generated by Xtext 2.21.0
 */
package oliv.form.xtext.fix.parser.antlr;

import com.google.inject.Inject;
import oliv.form.xtext.fix.parser.antlr.internal.InternalFixParser;
import oliv.form.xtext.fix.services.FixGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FixParser extends AbstractAntlrParser {

	@Inject
	private FixGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFixParser createParser(XtextTokenStream stream) {
		return new InternalFixParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public FixGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FixGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
